### ISSUE TITLE
delete events feature

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-trackercapture#111]

**Comment by ifoche** [comment]
An easy way to introduce it would be by sliding the event left/right, and then showing a confirmation pop-up ("Are you sure you want to delete this event?").

**Comment by manuelplazaspalacio** [comment]
There is a Pr in tracker capture that it isn't showing here. https://github.com/EyeSeeTea/dhis2-android-trackercapture/pull/130
