### ISSUE TITLE
Crash on XX TEST - SINGLESTAGE SingleCatCombo program

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-trackercapture#123]
server android-previous1, creating a new TEI, then a new event and on complete it crash

**Comment by manuelplazaspalacio** [comment]
Tested but can't replicate,  because we don't know how to configure the event like the testers do. We need the testers to create the program for replicate it.

**Comment by xurxodev** [comment]
the program 'XXTEST Tracker Rules' no longer exists
