### ISSUE TITLE
Unique attributes not respected

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-trackercapture#137]

**Comment by ifoche** [comment]
![53327864-169a-4db7-967b-d6cc0dfffe7d.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54e12dad64acc92700d55240/125516c66e82c728ace21e0d46bdc7c971d5dbffdba4ee15fd5cbdc02d44703e7052f4293d81b52bbc127f0709091bab154a4356bcbbd671f3e57862804e0ee4d03f5a20cf3447a8bdd449ea01b971831e8cb6ea8f19d2f42f67b6d5db1063474f4dcbed5727a29f41c95df64ae34f52a315346ae6762431.jpg)

**Comment by idelcano** [comment]
solved in #136

**Comment by xurxodev** [comment]
@idelcano this issue is not solved in #136, the problem is that on server a TEI attribute can be mark as unique and this logic in Android app not exists
