### ISSUE TITLE
Show the correct title when navigate a new activity from action buttons in new enrollment activity

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-trackercapture#14]
User reports this:
Dear Team,
While dealing with related programs such as a Household Program and Household Members program where we enroll a household using a household program and related to Household members, we need to add household members as relationships and followup household members through repeated stages.
This functional is well supported by the web, but not supported by the android tracker capture. You cant add a new relationship nor edit a web created relationship.
See attached picture

**Comment by ifoche** [comment]
![screenshot_20170524-202631](https://cloud.githubusercontent.com/assets/10931645/26619681/c60aafa8-45df-11e7-8c52-f8564d73bc64.png)

**Comment by ifoche** [comment]
Tested and it works. User needs to use the entity downloader. The only thing that's missing is the sections titles, that @idelcano is going to fix

**Comment by xurxodev** [comment]
original issue title: Not able to add a relationship nor edit a web created relationship with Android Tracker Capture
