### ISSUE TITLE
Handle Server error responses when synchronizing data

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-trackercapture#16]
These errors are produced when there is a heavy load on the server , requiring a restart.
The most noticeably errors that are prevalent are these http status error codes:
http 500 status error -query did not return a unique result
http 409 status error - The request could not be completed due to a conflict with the current state of the target resource
http 502 status error - related to bad gateway
The normally occur after the app has tried several times to synchronize data. As soon as it flags the records with errors they cannot be synchronized to the server again when services have been restored.
Suggested behavior: treat the error response as if there is no network connectivity by making the failed sync objects remain in "offline status".

**Comment by xurxodev** [comment]
I have two bugs in web api but not in app. I have send a email to dhis dev list:
---------------------------------------------
Hi, my name es Jorge Sánchez 

I have find 2 bugs in web api from tracker capture  app:

- The PUT request for enrollment end point always returns http code 500 internar error in server 
- Sometimes when I create a new enrollment and then create a new event for a program stage that has not events. When I send this event to sever, the web api returns http code 409 with the message ‘the program stage is not repeatable and there is already an event for the program stage’
Thanks

**Comment by ifoche** [comment]
@xurxodev you have answers on the Jira issues:
https://jira.dhis2.org/browse/DHIS2-1796
https://jira.dhis2.org/browse/DHIS2-1795

Could you please answer them? Thanks!
