### ISSUE TITLE
When creating a TEI from create relationships the new TEI show more details in the list than the previous one

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-trackercapture#174]

**Comment by idelcano** [comment]
![diferentesrows.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56153dcd2d55821100fa1eb5/125516c66e82c728ace21e0d46ec9d9c269086a79becac51ab4ae3d665043761260ea62864c7b96aea1b2a035a0b47a5175c5a12aaac8928f7be6d798a0a0eb8c3714d36976345f3e5db55ea43a82a994d84bcbd8f4cc4e03f25e6838746381b1755.png)
@xurxodev  we need talk tomorrow about this issue. As you can see in the image, each row is a different tei with different enrollment and different attributes.
