### ISSUE TITLE
Check conflicts in who events

### ISSUE THREAD

**Issue by idelcano** [EyeSeeTea/dhis2-android-trackercapture#185]
Tested in previous2

"conflicts":[  
               {  
                  "object":"EyfTU3ibMmJ",
                  "value":"value_not_bool"
               },
               {  
                  "object":"DwWIh6D3fSr",
                  "value":"value_not_true_only"
               }
            ], {  
                  "object":"EyfTU3ibMmJ",
                  "value":"value_not_bool"
               },
               {  
                  "object":"DwWIh6D3fSr",
                  "value":"value_not_true_only"
               }

{  
                  "object":"EyfTU3ibMmJ",
                  "value":"value_not_bool"
               }

  {  
                  "object":"EyfTU3ibMmJ",
                  "value":"value_not_bool"
               },
               {  
                  "object":"spkG704sTh6",
                  "value":"value_not_numeric"
               }

**Comment by xurxodev** [comment]
the problem is on the server, A data element with OptionSet should have text type and not yes/no type. On server, the error has occurred also. If data element is configured well sync work sucessfully
