### ISSUE TITLE
Review Program Rules (functions & actions) & implement missing ones

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-trackercapture#200]

**Comment by tokland** [comment]
## Functions

- tracker-capture-app -> d2-tracker, 25 functions:

    addControlDigits, addDays, ceil, checkControlDigits, concatenate, count, countIfValue, countIfZeroPos, daysBetween, floor, hasValue, lastEventDate, left, length, modulus, monthsBetween, oizp, right, round, split, substring, validatePattern, weeksBetween, yearsBetween, zing

    https://github.com/dhis2/d2-tracker/blob/master/src/dhis2.angular.services.js#L2000

- maintenance-app, 23 functions:
    
    addDays, ceil, concatenate, count, countIfValue, countIfZeroPos, daysBetween, floor, hasValue, left, length, modulus, monthsBetween, oizp, right, round, split, substring, validatePattern, weeksBetween, yearsBetween, zing, zpvc

    https://github.com/dhis2/maintenance-app/blob/master/src/config/field-overrides/program-rules/programRuleFunctions.js

- dhis2-android-sdk, 17 functions:

    addDays concatenate condition count countIfValue countIfZeroPos floor modulus monthsBetween oizp weeksBetween yearsBetween zing zpvc

    https://github.com/dhis2/dhis2-android-sdk/blob/2.23-legacy/core/src/main/java/org/hisp/dhis/android/sdk/utils/support/math/ExpressionFunctions.java

## Actions

- tracker-capture-app, 12 types:

    https://github.com/dhis2/tracker-capture-app/blob/v27/components/dataentry/dataentry-controller.js

    ASSIGN, CREATEEVENT, DISPLAYKEYVALUEPAIR, DISPLAYTEXT, ERRORONCOMPLETE, HIDEFIELD, HIDEPROGRAMSTAGE, HIDESECTION, SETMANDATORYFIELD, SHOWERROR, SHOWWARNING, WARNINGONCOMPLETE

- maintenance-app, 12 actions:

    https://github.com/dhis2/maintenance-app/blob/v27/src/config/field-overrides/program-rules/programRuleActionTypes.js

    ASSIGN, CREATEEVENT, DISPLAYKEYVALUEPAIR, DISPLAYTEXT, ERRORONCOMPLETE, HIDEFIELD, HIDEPROGRAMSTAGE, HIDESECTION, SETMANDATORYFIELD, SHOWERROR, SHOWWARNING, WARNINGONCOMPLETE

- dhis2-android-sdk/2.23-legacy
    
    - Defined 12 types:

    https://github.com/dhis2/dhis2-android-sdk/blob/2.23-legacy/core/src/main/java/org/hisp/dhis/android/sdk/utils/api/ProgramRuleActionType.java

    ASSIGN, CREATEEVENT, DISPLAYKEYVALUEPAIR, DISPLAYTEXT, ERRORONCOMPLETE, HIDEFIELD, HIDEPROGRAMSTAGE, HIDESECTION, SETMANDATORYFIELD, SHOWERROR, SHOWWARNING, WARNINGONCOMPLETE

    - But implemented 8 types:

    ASSIGN, CREATEEVENT, DISPLAYKEYVALUEPAIR, DISPLAYTEXT, HIDEFIELD, HIDESECTION, SHOWERROR, SHOWWARNING

    https://github.com/dhis2/dhis2-android-sdk/blob/2.23-legacy/core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/common/AbsProgramRuleFragment.java

**Comment by tokland** [comment]
TODO: Variables (event_date, etc) should be checked also.
