### ISSUE TITLE
Implement missing functions for Program Rules

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-trackercapture#219]
- [x] Tests for existing methods in ExpressionFunction.
 - [x] Implement missing methods (with tests)

**Comment by tokland** [comment]
tracker-capture-app -> d2-tracker, 25 functions:

addControlDigits, addDays, ceil, checkControlDigits, concatenate, count, countIfValue, countIfZeroPos, daysBetween, floor, hasValue, lastEventDate, left, length, modulus, monthsBetween, oizp, right, round, split, substring, validatePattern, weeksBetween, yearsBetween, zing

https://github.com/dhis2/d2-tracker/blob/master/src/dhis2.angular.services.js#L2000

maintenance-app, 23 functions:

addDays, ceil, concatenate, count, countIfValue, countIfZeroPos, daysBetween, floor, hasValue, left, length, modulus, monthsBetween, oizp, right, round, split, substring, validatePattern, weeksBetween, yearsBetween, zing, zpvc

https://github.com/dhis2/maintenance-app/blob/master/src/config/field-overrides/program-rules/programRuleFunctions.js

dhis2-android-sdk, 17 functions:

addDays, concatenate, condition, count, countIfValue, countIfZeroPos, daysBetween, floor, modulus, monthsBetween, oizp, weeksBetween, yearsBetween, zing, zpvc

https://github.com/dhis2/dhis2-android-sdk/blob/tracker-capture/core/src/main/java/org/hisp/dhis/android/sdk/utils/support/math/ExpressionFunctions.java
