### ISSUE TITLE
Review reloadProgramRules() execution while in ProgramOverviewFragment

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-trackercapture#236]

**Comment by ifoche** [comment]
reloading program rules while executing them...I'm not sure if this could have any consequence. Let's draw and determine exactly the execution path that program rules are following

**Comment by idelcano** [comment]
- [ ] Create a workflow diagram of the program rules in wiki.
- [ ] Modify if necessary ProgramOverviewFragment reloadProgramRules()

**Comment by idelcano** [comment]
![enrollmentdataentryfragment 2](https://user-images.githubusercontent.com/5302538/33226362-5e37d55c-d18c-11e7-9a42-683bb9f7970b.png)
![eventfragment](https://user-images.githubusercontent.com/5302538/33226364-611e7d52-d18c-11e7-9f8f-88fe13925ebd.png)
![trackedentityinstancedataentryfragment 1](https://user-images.githubusercontent.com/5302538/33226367-650f59e0-d18c-11e7-9d81-12eabe70cc88.png)
![trackedentityinstanceprofilefragment](https://user-images.githubusercontent.com/5302538/33226368-6750e5ca-d18c-11e7-8597-cf5ea71751fe.png)
![trackedentityinstanceattributeprofile program rule actions 1](https://user-images.githubusercontent.com/5302538/33226373-71aa8396-d18c-11e7-9512-5851121e62e4.png)
![trackedentityinstanceattributedateentry program rule actions 2](https://user-images.githubusercontent.com/5302538/33226375-77049958-d18c-11e7-94a6-f036b491ed4e.png)
![enrollments program rule actions](https://user-images.githubusercontent.com/5302538/33226377-7b8772de-d18c-11e7-999c-52adc7a43be5.png)
![programoverviewfragment](https://user-images.githubusercontent.com/5302538/33226382-8b5ac53a-d18c-11e7-9cc8-972c11730c08.png)
![programoverview program rule actions](https://user-images.githubusercontent.com/5302538/33226383-906c4602-d18c-11e7-8998-2f84303b9506.png)
![asynchelperthreadworkflow 1](https://user-images.githubusercontent.com/5302538/33226387-9d3d04f2-d18c-11e7-8de8-ac6215d8c7ec.png)

**Comment by idelcano** [comment]
![event program rule actions 2](https://user-images.githubusercontent.com/5302538/33226502-a13d5a4a-d18f-11e7-8e0c-e7fcf3a674bd.png)

**Comment by idelcano** [comment]
@ifoche  I think is not necessary  change the workflow used by programOverviewFragment  to update the program rules. But it is different than the other fragments as you can look in the diagrams
