### ISSUE TITLE
UI consistency with Event Capture

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-trackercapture#298]
Text from the client:

Tracker capture and Event Capture are pretty similar, By default events (and TEIs) have the floppy disc icon, then when you click on it, a pop-up opens saying that it is not synced, then you have two "sync arrows". When you click on them, then it is synced and

The difference is that in Event capture there is a text "Offline" below the floppy disc and "sent" below the green tick which helps understanding the two steps (local and server storage). I would suggest not changing anything on Event Capture and adapting tracker capture to event capture. It implies adding the text Offline or Sent whenever there is a yellow floppy disc or a green tick in Tracker Capture.

Tracker capture also uses another a different floppy disc (blue) to save a tracked entity instance while it is registered (first step). It is not ideal, but I do not think is very confusing. If you have any suggested icon for save that looks different, maybe we could change it.

**Comment by manuelplazaspalacio** [comment]
Asking to the client for the floppy disc icon replacement, if when merging we don't added yet, approve de issue and create  an other one to add the new icon.
