### ISSUE TITLE
Include "Age" Value-Type

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-trackercapture#8]
There's a new type called "Age" in 2.26 that is not supported by tracker capture. This is the message from the user that reports it.

Hello DHIS2 Community
I have created a program in Tracker capture with DHIS2 Version 2.26 and have been testing numerous datatypes within that program but the new "Age" valuetype only works on the Computer but is not functioning with the Tracker Capture App downloaded from Google Store.
On the Tracker Capture App, the "Age" Value type doesn't work in both Tracked entity Attributes and Data Elements.

**Comment by ifoche** [comment]
Not supported values:
Time/Unit interval/Percentage/Tracker assoc./File/Coordinate/OU/Age/URL

**Comment by ifoche** [comment]
A second issue was reported related to this one. The content reads as follows:
Error when synching TEI in TEI dashboard using Tracker Capture 0.3.36-2.26 from Play Store towards dev-server on 2017-03-03.
Using WHO RMNCH Tracker
Event: Antenatal care visit


DEs with type percentage & boolean (with option-set)
DEs:
EyfTU3ibMmJ	Clinical signs of extreme pallor	Appears as Yes/No/Unknown dropdown Value: Yes
X8HbdaoS9LN	WHOMCH Haematocrit value	Appears as long text field	Value: 7765
For percentage - API rejects all values that are not a whole number between 0 and 100. Would be good to have some in-app validations of this value type.

**Comment by idelcano** [comment]
The problem with the EyfTU3ibMmJ dataElement is in the type of the dataelement is Yes/false. When you re-select the dataElement optionset "Yes_No_Unkown", this change to the correct valuetype "text"
