### ISSUE TITLE
Option sets not syncing with Android until local data is cleared

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2-android-trackercapture#86]
When editing an existing or creating a new option set, the changes made will not sync with Android until local data is cleared.
If you edit an existing option set before clearing local data, the old entry options will display on Android.
If you create a new option set before clearing local data, a free text field will display allowing the user to input anything they wish (as seen in below screenshot). This will save locally on the device but will not sync if you have input incorrect characters, e.g "hello" in a data type int field.
In both circumstances, doing the following will sync option sets properly with Android:
Clearing cache & app data via Android settings
From the settings menu in app, selecting "Delete local data and log out"
Uninstall/re-install

**Comment by ifoche** [comment]
![dd20817c-cce0-4160-9ed0-d426a973ada6.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54e12dad64acc92700d55240/125516c66e82c728ace21e0d46ec90c873dad2fe8ca4bc40a10dbdc07810773e7001a77b3d81b77ae94322565c0e1afd474a4356bcbbd671f3e57862804e0ee4d03f5a20cf3447a8bdd449ea01b971831e8cb6ea8f19d2f42f67b6d5db1063474f4dcbed5727a29f41c95cff42e04453a0153e64e0762431.jpg)

**Comment by idelcano** [comment]
@ifoche  i think this was solved, i can't replicate it.
